name: Terraform apply
on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  terraform-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.10.3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4.0.2
        with:
          role-to-assume: ${{ secrets.ACCOUNT_ROLE_TO_ASSUME }}
          aws-region: "eu-central-1"

      - name: Terraform apply
        env:
          TF_VAR_rds_db_password: ${{ secrets.PRE_PROD_RDS_PASSWORD }}
        shell: bash
        run: |
          cd cloud_infrastructure
          terraform init -backend-config=backend-config.hcl
          terraform workspace select pre-prod || terraform workspace new pre-prod
          terraform apply -auto-approve -var-file=env_vars/pre-prod.tfvars -parallelism=10
